#!/bin/bash
# changelog.sh — Generate a structured CHANGELOG.md from git history
# Usage: bash changelog.sh [repo_path]
# Fetches commits since the last git tag, categorizes by conventional commit prefix

set -e

REPO_PATH="${1:-.}"
cd "$REPO_PATH"

# Check we're in a git repo
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "Error: Not a git repository: $REPO_PATH"
  exit 1
fi

# Get the last git tag (or start from initial commit if no tags)
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

if [ -z "$LAST_TAG" ]; then
  echo "No tags found. Using full commit history."
  COMMIT_RANGE=""
else
  echo "Last tag: $LAST_TAG"
  COMMIT_RANGE="$LAST_TAG..HEAD"
fi

# Fetch commits
COMMITS=$(git log $COMMIT_RANGE --format="%s" --no-merges 2>/dev/null || echo "")

if [ -z "$COMMITS" ]; then
  echo "No commits found."
  exit 0
fi

# Categorize commits into temp files (macOS bash 3.2 compatible)
ADDED_FILE=$(mktemp)
FIXED_FILE=$(mktemp)
CHANGED_FILE=$(mktemp)
REMOVED_FILE=$(mktemp)

while IFS= read -r line; do
  # Remove leading/trailing whitespace
  line="$(echo "$line" | xargs)"
  [ -z "$line" ] && continue

  # Classify by conventional commit prefix or keyword
  if echo "$line" | grep -qE "^(feat|add|new)[:\s]"; then
    echo "  - ${line}" >> "$ADDED_FILE"
  elif echo "$line" | grep -qE "^(fix|bug|patch)[:\s]"; then
    echo "  - ${line}" >> "$FIXED_FILE"
  elif echo "$line" | grep -qE "^(remove|delete|drop|rm|deprec)[:\s]"; then
    echo "  - ${line}" >> "$REMOVED_FILE"
  else
    echo "  - ${line}" >> "$CHANGED_FILE"
  fi
done <<< "$COMMITS"

# Generate CHANGELOG.md
VERSION="${LAST_TAG:-v1.0.0}"
DATE=$(date +"%Y-%m-%d")

{
  echo "# Changelog"
  echo ""
  echo "## [$VERSION] - $DATE"
  echo ""
  if [ -s "$ADDED_FILE" ]; then
    echo "### Added"
    echo ""
    cat "$ADDED_FILE"
    echo ""
  fi
  if [ -s "$FIXED_FILE" ]; then
    echo "### Fixed"
    echo ""
    cat "$FIXED_FILE"
    echo ""
  fi
  if [ -s "$CHANGED_FILE" ]; then
    echo "### Changed"
    echo ""
    cat "$CHANGED_FILE"
    echo ""
  fi
  if [ -s "$REMOVED_FILE" ]; then
    echo "### Removed"
    echo ""
    cat "$REMOVED_FILE"
    echo ""
  fi
  echo "*Generated by changelog.sh*"
} > CHANGELOG.md

# Cleanup
rm -f "$ADDED_FILE" "$FIXED_FILE" "$CHANGED_FILE" "$REMOVED_FILE"

echo "✅ CHANGELOG.md generated successfully!"
echo "📄 Output: $REPO_PATH/CHANGELOG.md"