#!/bin/bash
# changelog.sh — Generate a structured CHANGELOG.md from git history
# Usage: bash changelog.sh [repo_path]
# Fetches commits since the last git tag, categorizes by conventional commit prefix

set -e

REPO_PATH="${1:-.}"
cd "$REPO_PATH"

# Check we're in a git repo
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "Error: Not a git repository: $REPO_PATH"
  exit 1
fi

# Create temp files upfront (macOS bash 3.2 compatible)
ADDED_FILE=$(mktemp)
FIXED_FILE=$(mktemp)
CHANGED_FILE=$(mktemp)
REMOVED_FILE=$(mktemp)
COMMITS_FILE=$(mktemp)

# Get the last git tag (or start from initial commit if no tags)
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

if [ -z "$LAST_TAG" ]; then
  echo "No tags found. Using full commit history."
  # Write ALL commits to temp file (no range = full history)
  git log --format="%s" --no-merges > "$COMMITS_FILE" 2>/dev/null || true
else
  echo "Last tag: $LAST_TAG"
  # Write commits since last tag to temp file
  git log "$LAST_TAG..HEAD" --format="%s" --no-merges > "$COMMITS_FILE" 2>/dev/null || true
fi

if [ ! -s "$COMMITS_FILE" ]; then
  echo "No commits found."
  rm -f "$COMMITS_FILE" "$ADDED_FILE" "$FIXED_FILE" "$CHANGED_FILE" "$REMOVED_FILE"
  exit 0
fi

# Process each commit line with safe whitespace strip using parameter expansion
while IFS= read -r line || [ -n "$line" ]; do
  # Strip leading/trailing whitespace using bash param expansion
  line="${line#"${line%%[![:space:]]*}"}"
  line="${line%"${line##*[![:space:]]}"}"
  [ -z "$line" ] && continue

  # Classify by conventional commit prefix using extended grep
  # Feat/Add/New -> Added
  if echo "$line" | grep -qE "^feat|^add|^new"; then
    echo "  - ${line}" >> "$ADDED_FILE"
  # Fix/Bug/Patch -> Fixed
  elif echo "$line" | grep -qE "^fix|^bug|^patch"; then
    echo "  - ${line}" >> "$FIXED_FILE"
  # Remove/Delete/Drop/Rm/Deprec -> Removed
  elif echo "$line" | grep -qE "^remove|^delete|^drop|^rm|^deprec"; then
    echo "  - ${line}" >> "$REMOVED_FILE"
  # Everything else -> Changed
  else
    echo "  - ${line}" >> "$CHANGED_FILE"
  fi
done < "$COMMITS_FILE"

# Cleanup commits file
rm -f "$COMMITS_FILE"

# Generate CHANGELOG.md
VERSION="${LAST_TAG:-v1.0.0}"
DATE=$(date "+%Y-%m-%d")

{
  echo "# Changelog"
  echo ""
  echo "## [$VERSION] - $DATE"
  echo ""
  if [ -s "$ADDED_FILE" ]; then
    echo "### Added"
    echo ""
    cat "$ADDED_FILE"
    echo ""
  fi
  if [ -s "$FIXED_FILE" ]; then
    echo "### Fixed"
    echo ""
    cat "$FIXED_FILE"
    echo ""
  fi
  if [ -s "$CHANGED_FILE" ]; then
    echo "### Changed"
    echo ""
    cat "$CHANGED_FILE"
    echo ""
  fi
  if [ -s "$REMOVED_FILE" ]; then
    echo "### Removed"
    echo ""
    cat "$REMOVED_FILE"
    echo ""
  fi
  echo "*Generated by changelog.sh*"
} > CHANGELOG.md

# Cleanup temp files
rm -f "$ADDED_FILE" "$FIXED_FILE" "$CHANGED_FILE" "$REMOVED_FILE"

echo "✅ CHANGELOG.md generated successfully!"
echo "📄 Output: $REPO_PATH/CHANGELOG.md"